### ISSUE TITLE
No WebXR API detected

### ISSUE THREAD

**Issue by JsMarq96** [WonderlandEngine/emscripten-webxr#4]
I am having some difficulties integrating this webxr to my webgl renderer, failing the `webxr_init`; and by diggin arround, it seems like there is no WebXR API detected.

For example, the `navigator.xr` returns null, like the device does not even have support for the API, but on other, pure JS samples, it returns an `XRSystem` object.

EDIT: Forgot to say, the error calback returns a -2. I suppose that I missed some setup, or something like that...

**Comment by Squareys** [comment]
Hey @JsMarq96!

Sorry for the delayed reply, things got quite busy while releasing [Wonderland Engine 0.9.0](https://wonderlandengine.com/news/release-0.9.0).

What device, browser and OS are you using? If I'd make a super wild guess from the little context, it'd be that you're checking online published (HTTPS-hosted) versions for the pure JS samples and using an Oculus Quest via a local IP (http://192.168...) to access the local website with the emscripten-webxr on it. 

Without HTTPS, you don't have WebXR, only on localhost this requirement is relaxed.
Therefore the reported "no WebXR API" would be correct.

But that's just a _very_ wild guess!

Best,
Jonathan

**Comment by JsMarq96** [comment]
Sorry for the delayed answer also and congrats on 0.9.0!
And yeah it was the HTTPS... Sorry to bother with something in retrospective that obvious, I missed that one on the docs...

**Comment by Squareys** [comment]
No worries, it's a very common issue that everyone hits once in their WebXR career :)
